package ma.digency.gov.amc.utils.enumeration;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum CountryEnum {

    AF("AF","افغانستان","Afghanistan"),
    AX("AX","جزایر الند","Åland"),
    AL("AL","آلبانی","Albanie"),
    DZ("DZ","الجزایر","Algérie"),
    AS("AS","ساموآی آمریکا","Samoa américaines"),
    AD("AD","آندورا","Andorre"),
    AO("AO","آنگولا","Angola"),
    AI("AI","آنگویلا","Anguilla"),
    AQ("AQ","جنوبگان","Antarctique"),
    AG("AG","آنتیگوا و باربودا","Antigua-et-Barbuda"),
    AR("AR","آرژانتین","Argentine"),
    AM("AM","ارمنستان","Arménie"),
    AW("AW","آروبا","Aruba"),
    AU("AU","استرالیا","Australie"),
    AT("AT","اتریش","Autriche"),
    AZ("AZ","آذربایجان","Azerbaïdjan"),
    BS("BS","باهاما","Bahamas"),
    BH("BH","بحرین","Bahreïn"),
    BD("BD","بنگلادش","Bangladesh"),
    BB("BB","باربادوس","Barbade"),
   BY ("BY","بلاروس","Biélorussie"),
    BE("BE","بلژیک","Belgique"),
    BZ("BZ","بلیز","Belize"),
    BJ("BJ","بنین","Bénin"),
    BM("BM","برمودا","Bermudes"),
    BT("BT","بوتان","Bhoutan"),
    BO("BO","بولیوی","Bolivie"),
    BQ("BQ","بونیر","Bonaire, Saint-Eustache et Saba"),
    BA("BA","بوسنی و هرزگوین","Bosnie-Herzégovine"),
    BW("BW","بوتسوانا","Botswana"),
    BV("BV","جزیره بووه","Île Bouvet"),
    BR("BR","برزیل","Brésil"),
    IO("IO","قلمرو بریتانیا در اقیانوس هند","Territoire britannique de l'océan Indien"),
    UM("UM","جزایر کوچک حاشیه‌ای ایالات متحده آمریکا","Îles mineures éloignées des États-Unis"),
    VG("VG","جزایر ویرجین بریتانیا","Îles Vierges britanniques"),
    VI("VI","جزایر ویرجین آمریکا","Îles Vierges des États-Unis"),
    BN("BN","برونئی","Brunei"),
    BG("BG","بلغارستان","Bulgarie"),
    BF("BF","بورکینافاسو","Burkina Faso"),
    BI("BI","بوروندی","Burundi"),
    KH("KH","کامبوج","Cambodge"),
    CM("CM","کامرون","Cameroun"),
    CA("CA","کانادا","Canada"),
    CV("CV","کیپ ورد","Cap Vert"),
    KY("KY","جزایر کیمن","Îles Caïmans"),
    CF("CF","جمهوری آفریقای مرکزی","République centrafricaine"),
    TD("TD","چاد","Tchad"),
    CL("CL","شیلی","Chili"),
    CN("CN","چین","Chine"),
    CX("CX","جزیره کریسمس","Île Christmas"),
    CC("CC","جزایر کوکوس","Îles Cocos"),
    CO("CO","کلمبیا","Colombie"),
    KM("KM","کومور","Comores"),
    CG("CG","کنگو","Congo"),
    CD("CD","جمهوری کنگو","Congo (Rép. dém.)"),
    CK("CK","جزایر کوک","Îles Cook"),
    CR("CR","کاستاریکا","Costa Rica"),
    HR("HR","کرواسی","Croatie"),
    CU("CU","کوبا","Cuba"),
    CW("CW","کوراسائو","Curaçao"),
    CY("CY","قبرس","Chypre"),
    CZ("CZ","جمهوری چک","République tchèque"),
    DK("DK","دانمارک","Danemark"),
    DJ("DJ","جیبوتی","Djibouti"),
    DM("DM","دومینیکا","Dominique"),
    DO("DO","جمهوری دومینیکن","République dominicaine"),
    EC("EC","اکوادور","Équateur"),
    EG("EG","مصر","Égypte"),
    SV("SV","السالوادور","Salvador"),
    GO("GQ","گینه استوایی","Guinée-Équatoriale"),
    ER("ER","اریتره","Érythrée"),
    EE("EE","استونی","Estonie"),
    ET("ET","اتیوپی","Éthiopie"),
    FK("FK","جزایر فالکلند","Îles Malouines"),
    FO("FO","جزایر فارو","Îles Féroé"),
    FJ("FJ","فیجی","Fidji"),
    FI("FI","فنلاند","Finlande"),
    FR("FR","فرانسه","France"),
    GF("GF","گویان فرانسه","Guayane"),
    PF("PF","پلی‌نزی فرانسه","Polynésie française"),
    TF("TF","سرزمین‌های جنوبی و جنوبگانی فرانسه","Terres australes et antarctiques françaises"),
    GA("GA","گابن","Gabon"),
    GM("GM","گامبیا","Gambie"),
    GE("GE","گرجستان","Géorgie"),
    DE("DE","آلمان","Allemagne"),
    GH("GH","غنا","Ghana"),
    GI("GI","جبل‌طارق","Gibraltar"),
    GR("GR","یونان","Grèce"),
    GL("GL","گرینلند","Groenland"),
    GD("GD","گرنادا","Grenade"),
    GP("GP","جزیره گوادلوپ","Guadeloupe"),
    GU("GU","گوام","Guam"),
    GT("GT","گواتمالا","Guatemala"),
    GG("GG","گرنزی","Guernesey"),
    GN("GN","گینه","Guinée"),
    GW("GW","گینه بیسائو","Guinée-Bissau"),
    GY("GY","گویان","Guyane"),
    HT("HT","هائیتی","Haïti"),
    HM("HM","جزیره هرد و جزایر مک‌دونالد","Îles Heard-et-MacDonald"),
    VA("VA","سریر مقدس","voir Saint"),
    HN("HN","هندوراس","Honduras"),
    HK("HK","هنگ‌کنگ","Hong Kong"),
    HU("HU","مجارستان","Hongrie"),
    IS("IS","ایسلند","Islande"),
    IN("IN","هند","Inde"),
    ID("ID","اندونزی","Indonésie"),
    CI("CI","ساحل عاج","Côte d'Ivoire"),
    IR("IR","ایران","Iran"),
    IQ("IQ","عراق","Irak"),
    IE("IE","ایرلند","Irlande"),
    IM("IM","جزیره من","Île de Man"),
    IL("IL","اسرائیل","Israël"),
    IT("IT","ایتالیا","Italie"),
    JM("JM","جامائیکا","Jamaïque"),
    JP("JP","ژاپن","Japon"),
    JE("JE","جرزی","Jersey"),
    JO("JO","اردن","Jordanie"),
    KZ("KZ","قزاقستان","Kazakhstan"),
    KE("KE","کنیا","Kenya"),
    KI("KI","کیریباتی","Kiribati"),
    KW("KW","کویت","Koweït"),
    KG("KG","قرقیزستان","Kirghizistan"),
    LA("LA","لائوس","Laos"),
    LV("LV","لتونی","Lettonie"),
    LB("LB","لبنان","Liban"),
    LS("LS","لسوتو","Lesotho"),
    LR("LR","لیبریا","Liberia"),
    LY("LY","لیبی","Libye"),
    LI("LI","لیختن‌اشتاین","Liechtenstein"),
    LT("LT","لیتوانی","Lituanie"),
    LU("LU","لوکزامبورگ","Luxembourg"),
    MO("MO","مکائو","Macao"),
    MK("MK","","Macédoine"),
    MG("MG","ماداگاسکار","Madagascar"),
    MW("MW","مالاوی","Malawi"),
    MY("MY","مالزی","Malaisie"),
    MV("MV","مالدیو","Maldives"),
    ML("ML","مالی","Mali"),
    MT("MT","مالت","Malte"),
    MH("MH","جزایر مارشال","Îles Marshall"),
    MQ("MQ","مونتسرات","Martinique"),
    MR("MR","موریتانی","Mauritanie"),
    MU("MU","موریس","Île Maurice"),
    YT("YT","مایوت","Mayotte"),
    MX("MX","مکزیک","Mexique"),
    FM("FM","ایالات فدرال میکرونزی","Micronésie"),
    MD("MD","مولداوی","Moldavie"),
    MC("MC","موناکو","Monaco"),
    MN("MN","مغولستان","Mongolie"),
    ME("ME","مونته‌نگرو","Monténégro"),
    MS("MS","مایوت","Montserrat"),
    MA("MA","المغرب","Maroc"),
    MZ("MZ","موزامبیک","Mozambique"),
    MM("MM","میانمار","Myanmar"),
    NA("NA","نامیبیا","Namibie"),
    NR("NR","نائورو","Nauru"),
    NP("NP","نپال","Népal"),
    NL("NL","پادشاهی هلند","Pays-Bas"),
    NC("NC","کالدونیای جدید","Nouvelle-Calédonie"),
    NZ("NZ","نیوزیلند","Nouvelle-Zélande"),
    NI("NI","نیکاراگوئه","Nicaragua"),
    NE("NE","نیجر","Niger"),
    NG("NG","نیجریه","Nigéria"),
    NU("NU","نیووی","Niue"),
    NF("NF","جزیره نورفک","Île de Norfolk"),
    KP("KP","کره جنوبی","Corée du Nord"),
    MP("MP","جزایر ماریانای شمالی","Îles Mariannes du Nord"),
    NO("NO","نروژ","Norvège"),
    OM("OM","عمان","Oman"),
    PK("PK","پاکستان","Pakistan"),
    PW("PW","پالائو","Palaos"),
    PS("PS","فلسطین","Palestine"),
    PA("PA","پاناما","Panama"),
    PG("PG","پاپوآ گینه نو","Papouasie-Nouvelle-Guinée"),
    PY("PY","پاراگوئه","Paraguay"),
    PE("PE","پرو","Pérou"),
    PH("PH","جزایر الندفیلیپین","Philippines"),
    PN("PN","پیتکرن","Îles Pitcairn"),
    PL("PL","لهستان","Pologne"),
    PT("PT","پرتغال","Portugal"),
    PR("PR","پورتو ریکو","Porto Rico"),
    QA("QA","قطر","Qatar"),
    XK("XK","کوزوو",null),
    RE("RE","رئونیون","Réunion"),
    RO("RO","رومانی","Roumanie"),
    RU("RU","روسیه","Russie"),
    RW("RW","رواندا","Rwanda"),
    BL("BL","سن-بارتلمی","Saint-Barthélemy"),
    SH("SH","سنت هلنا، اسنشن و تریستان دا کونا","Sainte-Hélène"),
    KN("KN","سنت کیتس و نویس","Saint-Christophe-et-Niévès"),
    LC("LC","سنت لوسیا","Saint-Lucie"),
    MF("MF","سینت مارتن","Saint-Martin"),
    PM("PM","سن پیر و میکلن","Saint-Pierre-et-Miquelon"),
    VC("VC","سنت وینسنت و گرنادین‌ها","Saint-Vincent-et-les-Grenadines"),
    WS("WS","ساموآ","Samoa"),
    SM("SM","سان مارینو","Saint-Marin"),
    ST("ST","کواترو دو فرویرو","Sao Tomé-et-Principe"),
    SA("SA","عربستان سعودی","Arabie Saoudite"),
    SN("SN","سنگال","Sénégal"),
    RS("RS","صربستان","Serbie"),
    SC("SC","سیشل","Seychelles"),
    SL("SL","سیرالئون","Sierra Leone"),
    SG("SG","سنگاپور","Singapour"),
    SX("SX","سینت مارتن","Saint Martin (partie néerlandaise)"),
    SK("SK","اسلواکی","Slovaquie"),
    SI("SI","اسلوونی","Slovénie"),
    SB("SB","جزایر سلیمان","Îles Salomon"),
    SO("SO","سومالی","Somalie"),
    ZA("ZA","آفریقای جنوبی","Afrique du Sud"),
    GS("GS","جزایر جورجیای جنوبی و ساندویچ جنوبی","Géorgie du Sud-et-les Îles Sandwich du Sud"),
    KR("KR","کره شمالی","Corée du Sud"),
    SS("SS","سودان جنوبی","Soudan du Sud"),
    ES("ES","اسپانیا","Espagne"),
    LK("LK","سری‌لانکا","Sri Lanka"),
    SD("SD","سودان","Soudan"),
    SR("SR","سورینام","Surinam"),
    SJ("SJ","سوالبارد و یان ماین","Svalbard et Jan Mayen"),
    SZ("SZ","سوازیلند","Swaziland"),
    SE("SE","سوئد","Suède"),
    CH("CH","سوئیس","Suisse"),
    SY("SY","سوریه","Syrie"),
    TW("TW","تایوان","Taïwan"),
    TJ("TJ","تاجیکستان","Tadjikistan"),
    TZ("TZ","تانزانیا","Tanzanie"),
    TH("TH","تایلند","Thaïlande"),
    TL("TL","تیمور شرقی","Timor oriental"),
    TG("TG","توگو","Togo"),
    TK("TK","توکلائو","Tokelau"),
    TO("TO","تونگا","Tonga"),
    TT("TT","ترینیداد و توباگو","Trinité et Tobago"),
    TN("TN","تونس","Tunisie"),
    TR("TR","ترکیه","Turquie"),
    TM("TM","ترکمنستان","Turkménistan"),
    TC("TC","جزایر تورکس و کایکوس","Îles Turques-et-Caïques"),
    TV("TV","تووالو","Tuvalu"),
    UG("UG","اوگاندا","Uganda"),
    UA("UA","وکراین","Ukraine"),
    AE("AE","امارات متحده عربی","Émirats arabes unis"),
    GB("GB","بریتانیای کبیر و ایرلند شمالی","Royaume-Uni"),
    US("US","ایالات متحده آمریکا","États-Unis"),
    UY("UY","اروگوئه","Uruguay"),
    UZ("UZ","ازبکستان","Ouzbékistan"),
    VU("VU","وانواتو","Vanuatu"),
    VE("VE","ونزوئلا","Venezuela"),
    VN("VN","ویتنام","Viêt Nam"),
    WF("WF","والیس و فوتونا","Wallis-et-Futuna"),
    EH ("EH","جمهوری دموکراتیک عربی صحرا","Sahara Occidental"),
    YE("YE","یمن","Yémen"),
    ZM("ZM","زامبیا","Zambie"),
    ZW("ZW", "زیمباوه","Zimbabwe");

    private String id;
    private String nameAr;
    private String name;

    public static String arabLabel(String code,String languge){
        for(CountryEnum b : CountryEnum.values()){
            if(b.getId().equals(code)){
                return languge.equalsIgnoreCase("ar") ? b.getNameAr():b.getName() ;
            }
        }
        return "";
    }
}
